### ISSUE TITLE
AgendaでURLをPasteしてSubmitしたあと、URL欄がクリアされない

### ISSUE THREAD

**Issue by ghost** [gmkou/FikaNote#22]
AgendaでURLをPasteしてSubmitしたあと、URL欄がクリアされず直前にSubmitしたURLが残り続ける。
そのため、多重投稿が起きやすくなる。

**Comment by ghost** [comment]
Oh, 個人用アカウントじゃない方から流れてますね...

**Comment by gmkou** [comment]
うん、ミスった。

**Comment by gmkou** [comment]
あ、カトケンもミスってるのか。
