### ISSUE TITLE
URLのタイトルをとりなおす仕組みがほしい

### ISSUE THREAD

**Issue by sassy** [gmkou/FikaNote#55]
URLの先のタイトルが取得できなかった時に、
"UNNAMED URL" になってしまっているので、
こちらのタイトルを取得し直す仕組みがほしい

**Comment by gmkou** [comment]
+1

**Comment by gmkou** [comment]
基本的に一度で取れなかったらその後も取れない気がする。
#86 で対応とするのが妥当ではないだろうか。
