### ISSUE TITLE
URL投稿直後に再読み込みをしないとゴミ箱が表示されない

### ISSUE THREAD

**Issue by sassy** [gmkou/FikaNote#56]
投稿直後のURLにゴミ箱が表示されないので、
間違ったURLを投稿した後削除するのにリロードが必要。

![issue](https://cloud.githubusercontent.com/assets/459739/8471228/244833e6-20d1-11e5-9592-73aef3fba4c5.png)

**Comment by gmkou** [comment]
知ってたけどチケット切ってなかったですね。
対応必要。。。

**Comment by sassy** [comment]
thx.
