### ISSUE TITLE
実体参照が解決されないことがある。

### ISSUE THREAD

**Issue by sassy** [gmkou/FikaNote#66]
たとえば、&は `&amp;` になるはずが、`&amp;amp;` と、&amp;の&が&amp;に置き換わって登録されてしまい、タイトル等が表示されるときに `&amp;` と表示されてしまう。
(下記参照)

<img width="507" alt="2015-07-08 23 26 16" src="https://cloud.githubusercontent.com/assets/459739/8572688/d0a19ec4-25c8-11e5-93cf-a5a60f8640be.png">

**Comment by gmkou** [comment]
Fixed.
