### ISSUE TITLE
チャットで投稿できるシステム？

### ISSUE THREAD

**Issue by ghost** [gmkou/FikaNote#97]
作ってみたら面白いかも。
http://creately.com/diagram/ikgxvds41/eiz2JM7c4rUePra3eImqlVivfcA%3D

**Comment by sassy** [comment]
チャット僕も加わること可能ですか？

**Comment by gmkou** [comment]
あー、こっちのアカウントで投稿してた...orz メアドいただければInviteします。

**Comment by gmkou** [comment]
アカウント切り替えのため一旦クローズ。
